name: Android-CI

on:
  push:
    branches: 
      - master
      
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
          JVM_OPTS: -Xmx4G
        
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                ref: master
                
            - name: setup JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
                
            - name: Get dependencies
              run: |
                sudo -E apt-get update
                sudo -E apt-get -y install build-essential autoconf automake libtool git wget curl android-sdk
                sudo -E apt-get -y autoremove --purge
                sudo -E apt-get clean
                df -h
              
            - name: Make Gradle executable
              run: chmod +x ./gradlew
              
            - name: Pull Submodules
              run: git submodule update --init --recursive --remote
                
            - name: Download Go Libs
              run: curl -L https://github.com/trojan-gfw/igniter-go-libs/releases/download/1.10/golibs.aar > app/src/libs/golibs.aar
                
            - name: Download Dependencies
              run: bash ./gradlew androidDependencies

            - name: Run Tests
              run: bash ./gradlew lint test

            - name: Build with Gradle
              run: bash ./gradlew build

            - name: Initial build
              run: bash ./gradlew clean assembleRelease --no-daemon --stacktrace

            - name: Deploy Igniter
              run: bash ./gradlew crashlyticsUploadDistributionProductionRelease --stacktrace --debug --no-daemon

            - name: Upload
              uses: actions/upload-artifact@master
              with:
                name: app-release
                path: app/build/outputs/apk/release/app-release.apk
